### ISSUE TITLE
when using sniwflakes on airflow 

### ISSUE THREAD

**Issue by wael-sudo2** [TheMultii/snowflake-util#3]
File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/snowflake.py", line 167, in Snowflake
 def parse_discord_snowflake(self, snowflake: str) -> tuple[datetime, int, int, int]:
 TypeError: 'type' object is not subscriptable
`default_date_string = datetime.strptime("2023-5-7", '%Y-%m-%d')
        SnowClass = snowflake.Snowflake()
        discord_snowflake = SnowClass.generate_discord_snowflake(
            date=datetime(
                default_date_string.year,
                default_date_string.month,
                default_date_string.day,
                0,
                0,
                0,
                0
            )`

**Comment by TheMultii** [comment]
On Python 3.10/3.11 it works fine. I'll check it on python 3.7 in just a minute... or two 👀

**Comment by TheMultii** [comment]
Ok. It seems I mistakenly stated that this library works on older Python version - 3.7 and 3.8. These two versions don't allow me to specify types inside a tuple. I can import them from `__future__` or ignore those types and try to make a workaround, but I probably need some time to do that since I'm a little busy.

For now, please (if it's possible) update your Python version to at least Python 3.9 if you want to use this library. Python 3.7 is now an unmaintained release.

**Comment by TheMultii** [comment]
Oh, and I don't understand your handling of this library. You can just pass a datetime object to the `date' param.

```py
dt = datetime(2022, 1, 1, 16, 15, 0, 0)
flk = SnowClass.generate_discord_snowflake(worker=5, process=5, sequence=222, date=dt)
```
You don't have to create a new datetime object from the day, month, and year of one that was created earlier and assigned to a variable.

**Comment by TheMultii** [comment]
Thank you for this issue. I won't close it for now. I'll try to do something to support some older Python versions.

**Comment by TheMultii** [comment]
Fixed on the master branch, I’ll publish it to PyPI soon.
